### ISSUE TITLE
Winkey emulation

### ISSUE THREAD

**Issue by henryflower** [ok1cdj/OpenCWKeyerMK2#1]
Hi,

I have noticed the following with my Open CW Keyer MK2: I have compiled and uploaded the firmware without any changes to options:

- in DXLog, it recognises the device as a Winkey on startup but output fails; after re-initialising from within the DXLog interfaces menu it works perfectly.
- in Win-Test it fails to recognise it as a Winkey, consequently, no CW output.
- The test software that K1EL provides ( [WKscan and WKtest](https://www.k1elsystems.com/softwareX.html) ) also fails to recognise the device as a Winkey.

Is there an option in the Arduino header files that I need to set to get it working without flaws or am I missing another point somewhere?

Thanks.

**Comment by ok1cdj** [comment]
Hi, do you have jumper on back side of keyer pluged in ?
and check this config:
`#define OPTION_WINKEY_STRICT_HOST_OPEN               // require an admin host open Winkey command before doing any other commands
#define OPTION_WINKEY_2_SUPPORT                      // comment out to revert to Winkey version 1 emulation
#define OPTION_WINKEY_INTERRUPTS_MEMORY_REPEAT
//#define OPTION_WINKEY_UCXLOG_9600_BAUD              // use this only with UCXLog configured for Winkey 9600 baud mode
#define OPTION_WINKEY_2_HOST_CLOSE_NO_SERIAL_PORT_RESET  // (Required for Win-Test to function)
// #define OPTION_WINKEY_FREQUENT_STATUS_REPORT         // activate this to make Winkey emulation play better with RUMlog and RUMped
#define OPTION_WINKEY_IGNORE_LOWERCASE               // Enable for typical K1EL Winkeyer behavior (use for SkookumLogger version 1.10.14 and prior to workaround "r" bug)`

**Comment by henryflower** [comment]
Hi,

I did not realise that the jumper was needed. With the jumper plugged in it works as expected with all the different programmes that I mentioned before. Thanks for your help.

**Comment by ok1cdj** [comment]
Jumer is needed due diffrent  RTS/DTR usage of  the software. Remove jumper only when FW update is needed.

73 Ondra OK1CDJ
