### ISSUE TITLE
Reset Open CW Keyer 

### ISSUE THREAD

**Issue by DL1ABR** [ok1cdj/OpenCWKeyerMK2#2]
Hi everybody, 
I think I did something wrong via the buttons.
My fingers were too fast ;-)
My "Open CW Keyer MK2" says in "WKdemo"
openComm: Success
Attach WK: No Echo
The Keyer beeps HI when I power it on.
Bit it shows no other reactions either via buttons nor via WKdemo.
Any hints??
Does anybody know how to reset the keyer??
vy 73 de Franz

**Comment by ok1cdj** [comment]
Which version of SW ? How about reset  ? You need to have switch plugged in for normal use.

73 Ondra

**Comment by DL1ABR** [comment]
Hi Ondra.
After switching on the keyer it reports CW „HI“
the COM port can be opened, otherwise "Error: WK not Open". 
I have no access to the Keyer anymore.
I may have changed something while typing on the keys... 
Is it possible to „reset to factory settings“??
The switch – you mean PRG jumper?
This jumper is open. No jumper.

Vy 73, Franz - DL1ABR

 

Von: Ondrej Kolonicny ***@***.***> 
Gesendet: Donnerstag, 19. Oktober 2023 12:17
An: ok1cdj/OpenCWKeyerMK2 ***@***.***>
Cc: Franz ***@***.***>; Author ***@***.***>
Betreff: Re: [ok1cdj/OpenCWKeyerMK2] Reset Open CW Keyer (Issue #2)

 

Which version of SW ? How about reset ? You need to have switch plugged in for normal use.

73 Ondra

**Comment by ok1cdj** [comment]
When you use winkey, the **jumper on back side of keyer must be installed**. 

73 Ondra

**Comment by DL1ABR** [comment]
Hi, Ondra,

 

a little peace of thin wire helped.
Because I have no jumper.
And nobody has a 2 mm-jumper around here.
So a thin wire must do.


When I want to switch to „IAMBIC MODE A“ I must

1.	Take jumper off
2.	Connect to WKdemo
3.	Type „\a“ and „ENTER“
4.	And type „EXIT“ „ENTER“
5.	Disconnect from WKdemo

 

Is that correct??


vy 73 de

Franz – DL1ABR

 

 

Von: Ondrej Kolonicny ***@***.***> 
Gesendet: Donnerstag, 19. Oktober 2023 13:38
An: ok1cdj/OpenCWKeyerMK2 ***@***.***>
Cc: Franz ***@***.***>; Author ***@***.***>
Betreff: Re: [ok1cdj/OpenCWKeyerMK2] Reset Open CW Keyer (Issue #2)

 

When you use winkey, the jumper on back side of keyer must be installed.

73 Ondra

**Comment by ok1cdj** [comment]
The jumper will be off only when you upgrading firmware.  If you set Iambic A from winkey is it possible, but you need to have it connect as winkey.  Use command mode by button,  read the manual:
https://github.com/k3ng/k3ng_cw_keyer/wiki

73 Ondra OK1CDJ

**Comment by DL1ABR** [comment]
Thank you so much Ondra!!
Step by step I learn to use the keyer 😊
vy 73 de

Franz DL1ABR

 

Von: Ondrej Kolonicny ***@***.***> 
Gesendet: Sonntag, 22. Oktober 2023 21:28
An: ok1cdj/OpenCWKeyerMK2 ***@***.***>
Cc: Franz ***@***.***>; Author ***@***.***>
Betreff: Re: [ok1cdj/OpenCWKeyerMK2] Reset Open CW Keyer (Issue #2)

 

The jumper will be off only when you upgrading firmware. If you set Iambic A from winkey is it possible, but you need to have it connect as winkey. Use command mode by button, read the manual:
https://github.com/k3ng/k3ng_cw_keyer/wiki

73 Ondra OK1CDJ
